# Intent Classifier Training Configuration
seed: 75
cuda_id: 1

# Training parameters
n_epochs: 100
batch_size: 32
num_workers: 4

base_lr: 0.001
reg_coef: 0.0005

# Logging and saving
log_every_epoch: 100
snapshot_every_epoch: 10

# Model parameters
num_intents: 4

# Paths
work_dir: 'runs-classifier'
oishape_cfg: 'config/all_cate.yaml'
checkpoint: null